title: Sassy Squad
description: A sophisticated website for sophisticated people
show_downloads: true
minimal_mistakes_skin    : "default"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache