title: Sassy Squad

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  Sassy squad is a learning platform that teaches you sass
# The base hostname & protocol of your site for where absolute urls are needed
url: https://lwu1822.github.io/sassy_squad/

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
