theme: jekyll-theme-cayman
title: "Leuck Family Reunion"
description: "June 26 to July 1 2023"
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
